### ISSUE TITLE
Comparison to webpack-dll-bundles-plugin

### ISSUE THREAD

**Issue by cgatian** [asfktz/autodll-webpack-plugin#24]
What does this plugin do that [webpack-dll-bundles-plugin](https://github.com/shlomiassaf/webpack-dll-bundles-plugin) doesn't?  

Looking at the two plugins, they are very similar.

**Comment by asfktz** [comment]
Great question, @cgatian 

To be honest, I wasn't aware of webpack-dll-bundle-plugin when I wrote this one.

AutoDLL started as a humble PR for adding DLL support in create-react-app (CRA).
I intended to do so without adding more complexity to project.

That PR went over many iterations before I realized one day that the best way to do so is to encapsulate the entire logic into a Plugin. After doing so, I noticed there's nothing specific to CRA about it anymore and that other projects can benefit from it too. so I extracted AutoDLL into its own repo.

## Key differences

First, I must say that I have very little experience with webpack-dll-bundles-plugin,
So please correct me if you find any mistake in my notes.

### Cache dir
**DllBundles** asks you to specify its cache directory, which is also its output folder.
It is where it stores both the DLLs and its invalidation logic (the `dll-bundles-state.json` file).

**AutoDLL** hides that Away from you and uses [find-cache-dir](https://github.com/avajs/find-cache-dir) to stores its cache inside `node_modules/.cache`

That has the benefit of automaticity invalidating the cache every time `npm install`, `remove`, or `update` in called since the `.cache` dir gets delete every you use one of those commands.


### Webpack's dev-server support

**DllBundles** seems to create the DLLs in your project also when you use the dev-server.

One of webpack's dev-server features is that it stores the assets in the memory instead for, faster access, and allows you to access them if the were just regular files.

**AutoDLL** respects that and when the devServer is used, the DLLs added to the memory as well.

### Filenames
Seems like **DllBundles** doesn't allow to change the DLL's filename, and to get it you have to use an external API like so:

```js
  new AddAssetHtmlPlugin([
    { filepath: helpers.root(`dll/${DllBundlesPlugin.resolveFile('polyfills')}`) },
    { filepath: helpers.root(`dll/${DllBundlesPlugin.resolveFile('vendor')}`) }
  ])
```

**AutoDLL** handles it differently.
First, you can use any valid webpack filename template, by using the `filename` option:

```js
new AutoDllPlugin({
      path: './dll',
      filename: '[name].dll.js'
      entry: {
        vendor: [ ... ]
      },
      ...
    })
```

Then in the HTML you can use:

```html
<script src="/dll/vendor.dll.js"></script>
```

You might also want to use a filename template like so: `[name]_[hash].js`
Since the `hash` part is unpredictable, you have to inject the DLL bundle intro the HTML dynamically.

That's why AutoDLL recommends using the [HtmlPlugin](https://github.com/jantimon/html-webpack-plugin )
And by specifying `inject: true`, AutoDLL will inject the bundles for you

```js
plugins: [
    new HtmlWebpackPlugin({
      inject: true,
      template: './src/index.html',
    }),
    new AutoDllPlugin({
      inject: true, // ⟸
      context: __dirname,
      filename: '[name]_[hash].js',
      path: './dll',
      entry: {
        vendor: [
          'react',
          'react-dom',
          'moment'
        ]
      }
    })
  ]
```

Will result in

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Document</title>
</head>
<body>
  <script src="/dll/vendor.dll.js"></script>
  <script src="/main.bundle.js"></script>
</body>
</html>
```

### Invalidation
If I understood correctly, DllBundles checks the contents of each module's package.json

AutoDLL currently have to two conditions for invalidation
1. The existence of the .cache directory, as explained before.
2. If the current settings passed into the plugin are different from last time.

There's also a [very exciting PR](https://github.com/asfktz/autodll-webpack-plugin/pull/13) on the way, which will allow any change to be detected.

For examples, you'll be able to add `conosle.log` in `node_modules/angular`
and it will trigger a build on next run.

### Test
Currently, I don't see tests in DllBundles.

AutoDll design to be testable from the beginning, I believe it's important for the stability of the project.

### Documantaion

Although it's still much a WIP, I believe in having great documentation with many examples and FAQ. I intend AutoDLL to the have that.

**Comment by cgatian** [comment]
Wow, thank you @asfktz for the in depth comparison!

I look forward to integrating this into our project, once some of the bumps are cleaned up.  Thank you again. 🙏

**Comment by asfktz** [comment]
You're welcome, @cgatian  😊
