### ISSUE TITLE
Switch to pify instead of bluebird?

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#28]
Right now, `bluebird` is being used mainly for promisifying callback-style functions. Wouldn't it be better to use a lighter, more focused module like [`pify`](https://github.com/sindresorhus/pify) for this? [`Bluebird.join`](https://github.com/asfktz/autodll-webpack-plugin/blob/master/src/createMemory.js#L19) is also used but that can be achieved using `Promise.all` as suggested [here](https://github.com/sindresorhus/promise-fun#what-about-something-like-bluebirdjoin).

**Comment by asfktz** [comment]
I agree that `pify` is more suited if it was only for promisifying callbacks.
If fact, I used it earlier in the project.
But I really like bluebird's non-standard API.

Take a look at `createMemory`:  

```js
export const createMemory = (fs, cacheDir) => () => {
  const mfs = new MemoryFileSystem();

  return fs.readdirAsync(path.join(cacheDir, 'bundles'))
    .catch(() => [])
    .map(filename => join(
      filename,
      fs.readFileAsync(path.join(cacheDir, 'bundles', filename)))
    )
    .map(([filename, buffer]) => {
      mfs.writeFileSync(`/${filename}`, buffer);
    })
    .then(() => ({
      getBundles: getBundles.bind(null, mfs)
    }));
};
```

Isn't it much nicer to have the ability to map over promises like that?
What do you think?

(BTW, just notice I better change the second map to each, since it only contains a side effect and no mapping anything)

**Comment by sudo-suhas** [comment]
Sorry.. I didn't see that carefully. I like the `Bluebird.map` too. There is [`p-map`](https://github.com/sindresorhus/p-map) though. But it's better to use `bluebird` than add 2 dependencies.

**Comment by asfktz** [comment]
If I only count the times (or PRs) that you showed me that I didn't look carefully enough 😉

**Comment by sudo-suhas** [comment]
@asfktz Ha ha.. 2 sets of eyes better than 1
