### ISSUE TITLE
Watch Mode

### ISSUE THREAD

**Issue by asfktz** [asfktz/autodll-webpack-plugin#7]
Currently, the conditions for cache invalidation are:
1. npm `install` / npm `remove`
2. The plugin's settings are different from the last build.

As discussed in https://github.com/facebookincubator/create-react-app/pull/2710
Adding a watch functionality might be useful.

For examples, if someone adds a 'console.log()' in one of the node_modules, it will trigger a new build.

**Comment by viankakrisna** [comment]
For the watch option, I think it should be an array of resolved paths that we should watch.
```
{
  watch: [
     path.resolve('package.json'),
     path.resolve('package-lock.json'),
     path.resolve('yarn.lock'),
     path.resolve('node_modules')
     path.resolve('webpack.config.js')
  ]
}
```

And save hashes of those files and directory in the cache folder. So instead of just comparing JSON,  `isCacheValid` will compare hashes of files, folder, and setting. This would affect the initial build time but will make overall validation more accurate in the next start.

Then, the compiler needs to run in watch mode if `watch` property is truthy in the setting. I haven't thought through the implementation of this phase, should the main compiler run if the DLL compiler finished compiling?

**Comment by viankakrisna** [comment]
btw I've written a similar implementation of this plugin in [this CRA PR](https://github.com/facebookincubator/create-react-app/pull/1651/files). It would be nice if we can join the feature.

**Comment by asfktz** [comment]
Hi, @viankakrisna! good to see you here (:
I apologize for the late response, the real world got waaay too busy for me in the last few days.
Bad timing I guess 😅

Thanks for the PRs! I am eager to dive into it. That's my plan for tomorrow.

**Comment by viankakrisna** [comment]
No problem! Just ping me if you need anything :)

**Comment by asfktz** [comment]
Oh and one more thing!

Please keep in mind that more than one instances of the plugin can be used.
Like in this case: https://github.com/asfktz/autodll-webpack-plugin/issues/2#issuecomment-313000425

**Comment by viankakrisna** [comment]
that's making cleanup trickier, maybe we can set up a counter inside the constructor?

**Comment by viankakrisna** [comment]
updated https://github.com/asfktz/autodll-webpack-plugin/issues/13 with NODE_ENV and instance id
