### ISSUE TITLE
Integration tests failing on Windows

### ISSUE THREAD

**Issue by sudo-suhas** [asfktz/autodll-webpack-plugin#81]
```
λ yarn run test:integration
yarn run v1.3.2
$ node ./scripts/runIntegrationTests.js

> basic@1.0.0 test E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic
> ava --serial specs/*.integration.js

Starting the development server...

AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
AutoDllPlugin: is valid cache? true
clean run (cache deleted)
Starting the development server...

AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
AutoDllPlugin: is valid cache? true
second run (with cached dll bundle from previous run)
Starting the development server...

AutoDllPlugin: is valid cache? true
AutoDllPlugin: is valid cache? true

  2 failed

  detectPkgChange.integration » Detect package.json change
  Test finished without running any assertions

  retrieveStats.integration » Ensure stats retrieved from the currect source
  Test finished without running any assertions

npm ERR! Test failed.  See above for more details.
Done in 15.62s.
```

**Comment by asfktz** [comment]
I must admit that the integration test is not the clearest code I ever wrote,
it took me some time to wrap my head around it again.

I merged #82 and added a few console.logs, can you please run it again and paste the output?

**Comment by sudo-suhas** [comment]
@asfktz I don't see any new `console.log`s. Did you perhaps forget to push your changes?

**Comment by asfktz** [comment]
Oops! forgot to push. try now

**Comment by sudo-suhas** [comment]
Here you go:

```
λ yarn run test:integration
yarn run v1.3.2
$ node ./scripts/runIntegrationTests.js

> basic@1.0.0 test E:\Projects\repos\autodll-webpack-plugin\specs\fixtures\basic
> ava --serial specs/*.integration.js

Detect package.json change
Ensure stats retrieved from the currect source
clean run (cache deleted)
Starting the development server...

AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
first build is done.
change to package.json
making a change to some file to trigger a rebuild
AutoDllPlugin: is valid cache? true
Second build is done.
clean run (cache deleted)
Starting the development server...

AutoDllPlugin: is valid cache? false
AutoDllPlugin: cleanup
AutoDllPlugin: compile
AutoDllPlugin: is valid cache? true
second run (with cached dll bundle from previous run)
Starting the development server...

AutoDllPlugin: is valid cache? true
AutoDllPlugin: is valid cache? true

  2 failed

  detectPkgChange.integration » Detect package.json change
  Test finished without running any assertions

  retrieveStats.integration » Ensure stats retrieved from the currect source
  Test finished without running any assertions

npm ERR! Test failed.  See above for more details.
Done in 17.61s.
```

**Comment by asfktz** [comment]
Interesting... will take a deeper look at it later today

**Comment by sudo-suhas** [comment]
Sure. Let me know if you need help with anything. Once the integration tests are fixes, we should set up Appveyor integration.

**Comment by asfktz** [comment]
This is a diff between your output and mine:

![image](https://user-images.githubusercontent.com/199747/32702174-854e8636-c7eb-11e7-88f0-a985cb6e8c0c.png)

It seems like this part of the test is never called:
https://github.com/asfktz/autodll-webpack-plugin/blob/9f88ea13ef2f0576a9e9b10afa44ecc17a9c6d54/specs/fixtures/basic/specs/detectPkgChange.integration.js#L38-L49
(All that `routeCalls` is calling one callback at a time since this hook is called multiple times.
1st call - 1st callback. 2nd call - 2nd callback.)

The plugin calls the `autodll-stats-retrieved` hook after every DLL compile (only if needed)
The point of that hook was to test what was the source of the last build, was it a fresh build? or is it came from the cache (memory or FS)? it triggers the hook on line 68 in src/plugin.js:
https://github.com/asfktz/autodll-webpack-plugin/blob/9f88ea13ef2f0576a9e9b10afa44ecc17a9c6d54/src/plugin.js#L61-L75

I wonder if it is ever called `autodll-stats-retrieved` on windows...

Maybe we should setup Appveyor first, it's hard to debug it without being able to see it 😞

**Comment by sudo-suhas** [comment]
This is pretty weird but the integration tests seem to have fixed themselves. The issue may have been fixed when I ran `yarn` but I am not sure. I am closing this for now. Hopefully, I won't have to reopen this.

**Comment by asfktz** [comment]
Magic!! 🎩  ✨
