### ISSUE TITLE
Source maps are not created for dll bundle

### ISSUE THREAD

**Issue by WiseBird** [asfktz/autodll-webpack-plugin#89]
As issue title states problem is that source maps are created for main bundle and not for dll bundle:
![3](https://user-images.githubusercontent.com/1745378/33774295-e2d7ca3c-dc4b-11e7-9548-1ac6f8642884.png)

Webpack's config:
```js
module.exports = (env = {}) => {
    return {
        entry: './src/index.js',
        output: {
            filename: './bundle.js',
            path: path.resolve(__dirname, 'bundle'),
        },
        resolve: {
            extensions: ['.js']
        },
        plugins: [
            new HtmlWebpackPlugin({
                template: './src/index.html',
                inject: true,
                filename: "index.html",
            }),
            ...(env.dll ? [new AutoDllPlugin({
                inject: true,
                filename: '[name]_[hash].js',
                debug: false,
                entry: {
                    vendor_dll: ['jquery']
                },
            })] : []),
        ],
        devtool: "source-maps",
        devServer: {
            contentBase: path.join(__dirname, "bundle")
        }
    };
};
```

Reproduction - https://github.com/WiseBird/auto_dll_source_maps

- `npm i`
- Build with Dll Plugin - `npm run build:dll`
- Build without - `npm run build`

You can also run app with dll `npm run start:dll` and see in browser that code indeed lacks source maps:
![2](https://user-images.githubusercontent.com/1745378/33774616-df7b1104-dc4c-11e7-9b9b-cb7f3ab72927.png)

**Comment by sudo-suhas** [comment]
@WiseBird Thank you for the very through issue. By default, when the plugin creates the child-webpack config which compiles the DLL(as needed), it does not inherit from the parent config. Which is why the `devtool: 'source-maps'` is not propagated. This can be fixed by passing `inherit: true` in the `AutoDllPlugin` config:

```diff
diff --git a/webpack.config.js b/webpack.config.js
index 3b11684..80250c8 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -19,6 +19,7 @@ module.exports = (env = {}) => {
                 filename: "index.html",
             }),
             ...(env.dll ? [new AutoDllPlugin({
+                inherit: true,
                 inject: true,
                 filename: '[name]_[hash].js',
                 debug: false,
```

I tested this on the repo you had provided and I could see the source maps file `vendor_dll_cec34d33b53ddd985834.js.map` being created. 
I just realised that this option wasn't documented in the readme. I have created an issue(#90) for it and will document it at the earliest.

**Comment by WiseBird** [comment]
Thank you!
